---
title: Global Media Campaign to End FGM
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: false
url: https://www.globalmediacampaign.org
description: The Global Media Campaign is a non-profit organization that uses media
  to raise awareness about the harmful impact of Female Genital Mutilation by 'opening
  the airwaves' in countries with high prevalence.
permalink: pretty
exclude:
- bower.json
- package.json
- config.codekit3
- README*
- LICENSE*
- CHANGELOG*
- node_modules
- ".gitignore"
- bower_components
- assets/scss
plugins:
- jekyll-seo-tag
- jekyll-sitemap
- jekyll-feed
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
highlighter: rouge
colophon: http://garethjohnsdesign.com
company: Global Media Campaign To End FGM
email: 
analytics: 
logo: "/assets/img/logo.svg"
per_page: 12
date_format: "%d %B %Y"
future: true
social:
  instagram: 
compress_html:
  comments:
  - "<!-- "
  - " -->"
  blanklines: true
  profile: false
